name: Run Daily Price Tracker

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual run button

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grants explicit write access to the token

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Run Price Scraper Script
      run: python get_prices.py

    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update global item prices [skip ci]"
        file_pattern: 'data/global_prices.csv'
